name: Build TWRP for REDMAGIC_6S_PRO

on:
  push:
    branches:
      - main
      - twrp-12.1
  pull_request:
    branches:
      - main
      - twrp-12.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git \
          gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
          libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush \
          rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Set up repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Initialize repo
      run: |
        repo init -u https://github.com/piashmsubd/REDMAGIC_6S_PRO.git -b twrp-12.1
        repo sync -j$(nproc --all)

    - name: Build TWRP
      env:
        ALLOW_MISSING_DEPENDENCIES: true
        LC_ALL: C
      run: |
        source build/envsetup.sh
        lunch twrp_YOUR_DEVICE-eng
        make recoveryimage -j$(nproc --all)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: twrp-recovery-image
        path: out/target/product/YOUR_DEVICE/recovery.img
