name: EDK2 Porting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y git
        sudo apt-get install -y gcc-aarch64-linux-gnu
        sudo apt-get install -y device-tree-compiler

    - name: Clone EDK2 repo
      run: |
        git clone https://github.com/piashmsubd/edk2.git
        cd edk2
        git submodule update --init --recursive

    - name: Build EDK2 for Qualcomm SM8350
      run: |
        cd edk2
        source edksetup.sh
        make -C BaseTools
        build -a AARCH64 -t GCC5 -p Platforms/NX669J_12.1/NX669J_12.1.dsc

    - name: Package EDK2
      run: |
        mkdir -p output
        cp Build/NX669J_12.1/DEBUG_GCC5/FV/SM8350.fd output/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: edk2-boot-image
        path: output/SM8350.fd
        
        
        
    
